// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb42u5hi07_GK87Q6E-e-PQJnODiljE6A',
    appId: '1:952684436380:web:e72a67d229a68fbd3b4659',
    messagingSenderId: '952684436380',
    projectId: 'vitabear-v1',
    authDomain: 'vitabear-v1.firebaseapp.com',
    storageBucket: 'vitabear-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0fn74jtG2IVbO4GEQmfqN5q0AKnamnzs',
    appId: '1:952684436380:android:521e3540c799ccd63b4659',
    messagingSenderId: '952684436380',
    projectId: 'vitabear-v1',
    storageBucket: 'vitabear-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR_VZnpB9F2lGmKjt7I3Euj8Q7nGG0Z84',
    appId: '1:952684436380:ios:8e5666df107781ea3b4659',
    messagingSenderId: '952684436380',
    projectId: 'vitabear-v1',
    storageBucket: 'vitabear-v1.appspot.com',
    iosBundleId: 'com.samsacoder.vitabearsiparishatti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb42u5hi07_GK87Q6E-e-PQJnODiljE6A',
    appId: '1:952684436380:web:e3f5115ebf47ed9e3b4659',
    messagingSenderId: '952684436380',
    projectId: 'vitabear-v1',
    authDomain: 'vitabear-v1.firebaseapp.com',
    storageBucket: 'vitabear-v1.appspot.com',
  );
}
